envs:
  repo: https://github.com/farrukh90/artemis
  app_version:  "1.0.0"
  project_id: "gduzbyqwhqloandy"
  app_name:    "artemis"
  
  
  name: ContinuousDelivery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Clone a repo
        run: |
          git clone ${{ repo }}


    
      # Runs a set of commands using the runners shell
      - name: Switch Branches
        working-directory: nodejs
        run: |
          git checkout ${{1.0.0}}
          ls -l 


 # Runs a set of commands using the runners shell
      - name: Build Image
        working-directory: nodejs
        run: |
          docker build -t nodejs:${{ image_tag }}   .


          
       # Runs a set of commands using the runners shell
      - name: Tag Image
        working-directory: nodejs
        run: |
          docker image tag nodejs:${{ image_tag }} us-central1-docker.pkg.dev/${{ project_id }}/nodejs/nodejs:${{ image_tag }}



      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: gcloud version 



      - name: Authenticate to Google account
        run: |
          gcloud auth activate-service-account --key-file="service-account.json"
          gcloud config set project ${{ project_id }}



      - name: Authenticate to repository
        run: |
          gcloud auth configure-docker  us-central1-docker.pkg.dev

          


      # Runs a set of commands using the runners shell
      - name: Image push
        working-directory: nodejs
        run: |
          docker push us-central1-docker.pkg.dev/${{ project_id }}/nodejs/nodejs:${{ image_tag }}  
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: gcloud version 



      - name: Authenticate to Google Account
        run: |
          gcloud auth activate-service-account --key-file="service-account.json"
          gcloud config set project gduzbyqwhqloandy
          


      - name: Authenticate to repository
        run: |
          gcloud auth configure-docker  us-central1-docker.pkg.dev



    # Runs a set of commands using the runners shell
      - name: Image push
        working-directory: nodejs
        run: |
          docker push nodejs:1.0.0 us-central1-docker.pkg.dev/gduzbyqwhqloandy/nodejs/nodejs:1.0.0  




